# -*- coding: utf-8 -*-
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_execute_window(object):
    def setupUi(self, execute_window):
        execute_window.setObjectName("execute_window")
        execute_window.setWindowModality(QtCore.Qt.ApplicationModal)
        execute_window.resize(400, 300)
        execute_window.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(execute_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.execute_line = QtWidgets.QLineEdit(execute_window)
        self.execute_line.setObjectName("execute_line")
        self.horizontalLayout.addWidget(self.execute_line)
        self.execute_btn = QtWidgets.QPushButton(execute_window)
        self.execute_btn.setObjectName("execute_btn")
        self.horizontalLayout.addWidget(self.execute_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.execute_result = QtWidgets.QTextBrowser(execute_window)
        self.execute_result.setObjectName("execute_result")
        self.verticalLayout.addWidget(self.execute_result)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(execute_window)
        QtCore.QMetaObject.connectSlotsByName(execute_window)

    def retranslateUi(self, execute_window):
        _translate = QtCore.QCoreApplication.translate
        execute_window.setWindowTitle(_translate("execute_window", "Execute.."))
        self.execute_btn.setText(_translate("execute_window", "execute"))

class Ui_edit_case_persons_window(object):
    def setupUi(self, edit_case_persons_window):
        edit_case_persons_window.setObjectName("edit_case_persons_window")
        edit_case_persons_window.setWindowModality(QtCore.Qt.ApplicationModal)
        edit_case_persons_window.resize(300, 350)
        edit_case_persons_window.setMinimumSize(QtCore.QSize(250, 300))
        self.gridLayout = QtWidgets.QGridLayout(edit_case_persons_window)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.persons_view = QtWidgets.QTableWidget(edit_case_persons_window)
        self.persons_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.persons_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.persons_view.setColumnCount(3)
        self.persons_view.setObjectName("persons_view")
        self.persons_view.setRowCount(0)
        self.persons_view.horizontalHeader().setVisible(True)
        self.persons_view.horizontalHeader().setCascadingSectionResizes(False)
        self.persons_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.persons_view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(edit_case_persons_window)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_2.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(edit_case_persons_window)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_2.addWidget(self.delete_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.setStretch(0, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(edit_case_persons_window)
        QtCore.QMetaObject.connectSlotsByName(edit_case_persons_window)

    def retranslateUi(self, edit_case_persons_window):
        _translate = QtCore.QCoreApplication.translate
        edit_case_persons_window.setWindowTitle(_translate("edit_case_persons_window", "Form"))
        self.add_btn.setText(_translate("edit_case_persons_window", "添加"))
        self.delete_btn.setText(_translate("edit_case_persons_window", "删除"))

class Ui_persons_window(object):
    def setupUi(self, persons_window):
        persons_window.setObjectName("persons_window")
        persons_window.setWindowModality(QtCore.Qt.ApplicationModal)
        persons_window.resize(550, 350)
        persons_window.setMinimumSize(QtCore.QSize(400, 300))
        self.gridLayout = QtWidgets.QGridLayout(persons_window)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(persons_window)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.search_bar = QtWidgets.QLineEdit(persons_window)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout.addWidget(self.search_bar)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.results_view = QtWidgets.QTableWidget(persons_window)
        self.results_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.results_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.results_view.setColumnCount(2)
        self.results_view.setObjectName("results_view")
        self.results_view.setRowCount(0)
        self.results_view.horizontalHeader().setVisible(False)
        self.results_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.results_view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.add_btn = QtWidgets.QPushButton(persons_window)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout_2.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(persons_window)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_2.addWidget(self.delete_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(3, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.infos_view = QtWidgets.QTableWidget(persons_window)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.infos_view.setFont(font)
        self.infos_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.infos_view.setColumnCount(2)
        self.infos_view.setObjectName("infos_view")
        self.infos_view.setRowCount(0)
        self.infos_view.horizontalHeader().setVisible(False)
        self.infos_view.verticalHeader().setCascadingSectionResizes(True)
        self.infos_view.verticalHeader().setDefaultSectionSize(30)
        self.infos_view.verticalHeader().setMinimumSectionSize(30)
        self.horizontalLayout_3.addWidget(self.infos_view)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(persons_window)
        QtCore.QMetaObject.connectSlotsByName(persons_window)

    def retranslateUi(self, persons_window):
        _translate = QtCore.QCoreApplication.translate
        persons_window.setWindowTitle(_translate("persons_window", "Form"))
        self.label.setText(_translate("persons_window", "检索："))
        self.add_btn.setText(_translate("persons_window", "新建"))
        self.delete_btn.setText(_translate("persons_window", "删除"))

class Ui_new_project_window(object):
    def setupUi(self, new_project_window):
        new_project_window.setObjectName("new_project_window")
        new_project_window.setWindowModality(QtCore.Qt.ApplicationModal)
        new_project_window.resize(364, 211)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(new_project_window)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, 3, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 7, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(new_project_window)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.project_name_line = QtWidgets.QLineEdit(new_project_window)
        self.project_name_line.setPlaceholderText("")
        self.project_name_line.setObjectName("project_name_line")
        self.horizontalLayout.addWidget(self.project_name_line)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 7, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(new_project_window)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.project_num_line = QtWidgets.QLineEdit(new_project_window)
        self.project_num_line.setText("")
        self.project_num_line.setObjectName("project_num_line")
        self.horizontalLayout_2.addWidget(self.project_num_line)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(new_project_window)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.project_path_line = QtWidgets.QLineEdit(new_project_window)
        self.project_path_line.setText("")
        self.project_path_line.setReadOnly(True)
        self.project_path_line.setObjectName("project_path_line")
        self.horizontalLayout_3.addWidget(self.project_path_line)
        self.project_path_btn = QtWidgets.QPushButton(new_project_window)
        self.project_path_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.project_path_btn.setObjectName("project_path_btn")
        self.horizontalLayout_3.addWidget(self.project_path_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.project_ok_btn = QtWidgets.QPushButton(new_project_window)
        self.project_ok_btn.setEnabled(False)
        self.project_ok_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.project_ok_btn.setObjectName("project_ok_btn")
        self.horizontalLayout_4.addWidget(self.project_ok_btn)
        self.project_cancel_btn = QtWidgets.QPushButton(new_project_window)
        self.project_cancel_btn.setObjectName("project_cancel_btn")
        self.horizontalLayout_4.addWidget(self.project_cancel_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(new_project_window)
        QtCore.QMetaObject.connectSlotsByName(new_project_window)

    def retranslateUi(self, new_project_window):
        _translate = QtCore.QCoreApplication.translate
        new_project_window.setWindowTitle(_translate("new_project_window", "新的项目"))
        self.label.setText(_translate("new_project_window", "项目名："))
        self.label_2.setText(_translate("new_project_window", "项目号："))
        self.label_3.setText(_translate("new_project_window", "文件夹："))
        self.project_path_btn.setText(_translate("new_project_window", "..."))
        self.project_ok_btn.setText(_translate("new_project_window", "确定"))
        self.project_cancel_btn.setText(_translate("new_project_window", "取消"))

class Ui_template_window(object):
    def setupUi(self, template_window):
        template_window.setObjectName("template_window")
        template_window.setWindowModality(QtCore.Qt.ApplicationModal)
        template_window.resize(500, 250)
        template_window.setMinimumSize(QtCore.QSize(400, 300))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(template_window)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.class_list_view = QtWidgets.QListWidget(template_window)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.class_list_view.setFont(font)
        self.class_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.class_list_view.setObjectName("class_list_view")
        self.horizontalLayout.addWidget(self.class_list_view)
        self.item_list_view = QtWidgets.QTableWidget(template_window)
        self.item_list_view.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.item_list_view.setFont(font)
        self.item_list_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.item_list_view.setShowGrid(True)
        self.item_list_view.setGridStyle(QtCore.Qt.DotLine)
        self.item_list_view.setRowCount(0)
        self.item_list_view.setColumnCount(3)
        self.item_list_view.setObjectName("item_list_view")
        self.item_list_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.item_list_view.horizontalHeader().setVisible(False)
        self.item_list_view.verticalHeader().setVisible(False)
        self.item_list_view.verticalHeader().setDefaultSectionSize(25)
        self.item_list_view.verticalHeader().setMinimumSectionSize(18)
        self.horizontalLayout.addWidget(self.item_list_view)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.new_class_btn = QtWidgets.QPushButton(template_window)
        self.new_class_btn.setObjectName("new_class_btn")
        self.verticalLayout.addWidget(self.new_class_btn)
        self.delete_class_btn = QtWidgets.QPushButton(template_window)
        self.delete_class_btn.setObjectName("delete_class_btn")
        self.verticalLayout.addWidget(self.delete_class_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.new_item_btn = QtWidgets.QPushButton(template_window)
        self.new_item_btn.setObjectName("new_item_btn")
        self.verticalLayout.addWidget(self.new_item_btn)
        self.delete_item_btn = QtWidgets.QPushButton(template_window)
        self.delete_item_btn.setObjectName("delete_item_btn")
        self.verticalLayout.addWidget(self.delete_item_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(template_window)
        self.class_list_view.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(template_window)

    def retranslateUi(self, template_window):
        _translate = QtCore.QCoreApplication.translate
        template_window.setWindowTitle(_translate("template_window", "模板.."))
        self.new_class_btn.setText(_translate("template_window", "新增类别"))
        self.delete_class_btn.setText(_translate("template_window", "删除类别"))
        self.new_item_btn.setText(_translate("template_window", "新增字段"))
        self.delete_item_btn.setText(_translate("template_window", "删除字段"))

class Ui_today_news_window(object):
    def setupUi(self, today_news_window):
        today_news_window.setObjectName("today_news_window")
        today_news_window.setWindowModality(QtCore.Qt.ApplicationModal)
        today_news_window.resize(550, 400)
        self.gridLayout = QtWidgets.QGridLayout(today_news_window)
        self.gridLayout.setObjectName("gridLayout")
        self.message_view = QtWidgets.QTextBrowser(today_news_window)
        self.message_view.setObjectName("message_view")
        self.gridLayout.addWidget(self.message_view, 0, 0, 1, 1)

        self.retranslateUi(today_news_window)
        QtCore.QMetaObject.connectSlotsByName(today_news_window)

    def retranslateUi(self, today_news_window):
        _translate = QtCore.QCoreApplication.translate
        today_news_window.setWindowTitle(_translate("today_news_window", "TODO LIST"))

class Ui_person_info_window(object):
    def setupUi(self, person_info_window):
        person_info_window.setObjectName("person_info_window")
        person_info_window.setWindowModality(QtCore.Qt.ApplicationModal)
        person_info_window.resize(550, 400)
        self.gridLayout = QtWidgets.QGridLayout(person_info_window)
        self.gridLayout.setObjectName("gridLayout")
        self.infos_view = QtWidgets.QTableWidget(person_info_window)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.infos_view.setFont(font)
        self.infos_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.infos_view.setColumnCount(3)
        self.infos_view.setObjectName("infos_view")
        self.infos_view.setRowCount(0)
        self.infos_view.horizontalHeader().setVisible(False)
        self.infos_view.verticalHeader().setCascadingSectionResizes(True)
        self.infos_view.verticalHeader().setDefaultSectionSize(30)
        self.infos_view.verticalHeader().setMinimumSectionSize(30)
        self.gridLayout.addWidget(self.infos_view, 0, 0, 1, 1)
        self.retranslateUi(person_info_window)
        QtCore.QMetaObject.connectSlotsByName(person_info_window)

    def retranslateUi(self, person_info_window):
        _translate = QtCore.QCoreApplication.translate
        person_info_window.setWindowTitle(_translate("person_info_window", "Form"))


