# -*- coding: utf-8 -*-
from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_execute_window(object):
    def setupUi(self, execute_window):
        execute_window.setObjectName("execute_window")
        execute_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        execute_window.resize(400, 300)
        execute_window.setMinimumSize(QtCore.QSize(400, 300))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(execute_window)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.execute_line = QtWidgets.QLineEdit(execute_window)
        self.execute_line.setObjectName("execute_line")
        self.horizontalLayout.addWidget(self.execute_line)
        self.execute_btn = QtWidgets.QPushButton(execute_window)
        self.execute_btn.setObjectName("execute_btn")
        self.horizontalLayout.addWidget(self.execute_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.execute_result = QtWidgets.QTextBrowser(execute_window)
        self.execute_result.setObjectName("execute_result")
        self.verticalLayout.addWidget(self.execute_result)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(execute_window)
        QtCore.QMetaObject.connectSlotsByName(execute_window)

    def retranslateUi(self, execute_window):
        _translate = QtCore.QCoreApplication.translate
        execute_window.setWindowTitle(_translate("execute_window", "Execute.."))
        self.execute_btn.setText(_translate("execute_window", "execute"))

class Ui_edit_case_persons_window(object):
    def setupUi(self, edit_case_persons_window):
        edit_case_persons_window.setObjectName("edit_case_persons_window")
        edit_case_persons_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        edit_case_persons_window.resize(349, 393)
        edit_case_persons_window.setMinimumSize(QtCore.QSize(250, 300))
        self.gridLayout_3 = QtWidgets.QGridLayout(edit_case_persons_window)
        self.gridLayout_3.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 0, 12)
        self.gridLayout.setHorizontalSpacing(9)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.add_btn = QtWidgets.QToolButton(parent=edit_case_persons_window)
        self.add_btn.setText("")
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 1, 1, 1, 1)
        self.delete_btn = QtWidgets.QToolButton(parent=edit_case_persons_window)
        self.delete_btn.setText("")
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 5, 1, 1)
        self.up_down_btn = QtWidgets.QToolButton(parent=edit_case_persons_window)
        self.up_down_btn.setText("")
        self.up_down_btn.setObjectName("up_down_btn")
        self.gridLayout.addWidget(self.up_down_btn, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.persons_view = QtWidgets.QTableWidget(parent=edit_case_persons_window)
        self.persons_view.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.persons_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.persons_view.setColumnCount(3)
        self.persons_view.setObjectName("persons_view")
        self.persons_view.setRowCount(0)
        self.persons_view.horizontalHeader().setVisible(True)
        self.persons_view.horizontalHeader().setCascadingSectionResizes(False)
        self.persons_view.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.persons_view, 0, 0, 2, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.close_btn = QtWidgets.QToolButton(parent=edit_case_persons_window)
        self.close_btn.setMinimumSize(QtCore.QSize(65, 30))
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(edit_case_persons_window)
        QtCore.QMetaObject.connectSlotsByName(edit_case_persons_window)

    def retranslateUi(self, edit_case_persons_window):
        _translate = QtCore.QCoreApplication.translate
        edit_case_persons_window.setWindowTitle(_translate("edit_case_persons_window", "Form"))

class Ui_persons_window(object):
    def setupUi(self, persons_window):
        persons_window.setObjectName("persons_window")
        persons_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        persons_window.resize(600, 400)
        persons_window.setMinimumSize(QtCore.QSize(400, 300))
        self.gridLayout_3 = QtWidgets.QGridLayout(persons_window)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=persons_window)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(parent=self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.results_view = QtWidgets.QTableWidget(parent=self.widget)
        self.results_view.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.results_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.results_view.setColumnCount(2)
        self.results_view.setObjectName("results_view")
        self.results_view.setRowCount(0)
        self.results_view.horizontalHeader().setVisible(False)
        self.results_view.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.results_view, 0, 0, 2, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 15, 15)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 27, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.add_btn = QtWidgets.QToolButton(parent=self.widget)
        self.add_btn.setText("")
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.infos_view = QtWidgets.QTableWidget(parent=self.splitter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.infos_view.setFont(font)
        self.infos_view.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.infos_view.setColumnCount(2)
        self.infos_view.setObjectName("infos_view")
        self.infos_view.setRowCount(0)
        self.infos_view.horizontalHeader().setVisible(False)
        self.infos_view.verticalHeader().setCascadingSectionResizes(True)
        self.infos_view.verticalHeader().setDefaultSectionSize(30)
        self.infos_view.verticalHeader().setMinimumSectionSize(30)
        self.gridLayout_3.addWidget(self.splitter, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(13, 27, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.choose_btn = QtWidgets.QToolButton(parent=persons_window)
        self.choose_btn.setMinimumSize(QtCore.QSize(65, 30))
        self.choose_btn.setObjectName("choose_btn")
        self.horizontalLayout_2.addWidget(self.choose_btn)
        spacerItem3 = QtWidgets.QSpacerItem(13, 27, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_bar = QtWidgets.QLineEdit(parent=persons_window)
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout.addWidget(self.search_bar)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.setRowStretch(1, 1)

        self.retranslateUi(persons_window)
        QtCore.QMetaObject.connectSlotsByName(persons_window)

    def retranslateUi(self, persons_window):
        _translate = QtCore.QCoreApplication.translate
        persons_window.setWindowTitle(_translate("persons_window", "Form"))
        self.choose_btn.setText(_translate("persons_window", "选择"))

class Ui_today_news_window(object):
    def setupUi(self, today_news_window):
        today_news_window.setObjectName("today_news_window")
        today_news_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        today_news_window.resize(550, 400)
        self.gridLayout = QtWidgets.QGridLayout(today_news_window)
        self.gridLayout.setObjectName("gridLayout")
        self.message_view = QtWidgets.QTextBrowser(today_news_window)
        self.message_view.setObjectName("message_view")
        self.gridLayout.addWidget(self.message_view, 0, 0, 1, 1)

        self.retranslateUi(today_news_window)
        QtCore.QMetaObject.connectSlotsByName(today_news_window)

    def retranslateUi(self, today_news_window):
        _translate = QtCore.QCoreApplication.translate
        today_news_window.setWindowTitle(_translate("today_news_window", "TODO LIST"))

class Ui_person_info_window(object):
    def setupUi(self, person_info_window):
        person_info_window.setObjectName("person_info_window")
        person_info_window.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        person_info_window.resize(550, 400)
        self.gridLayout = QtWidgets.QGridLayout(person_info_window)
        self.gridLayout.setObjectName("gridLayout")
        self.infos_view = QtWidgets.QTableWidget(person_info_window)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.infos_view.setFont(font)
        self.infos_view.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.infos_view.setColumnCount(3)
        self.infos_view.setObjectName("infos_view")
        self.infos_view.setRowCount(0)
        self.infos_view.horizontalHeader().setVisible(False)
        self.infos_view.verticalHeader().setCascadingSectionResizes(True)
        self.infos_view.verticalHeader().setDefaultSectionSize(30)
        self.infos_view.verticalHeader().setMinimumSectionSize(30)
        self.gridLayout.addWidget(self.infos_view, 0, 0, 1, 1)
        self.retranslateUi(person_info_window)
        QtCore.QMetaObject.connectSlotsByName(person_info_window)

    def retranslateUi(self, person_info_window):
        _translate = QtCore.QCoreApplication.translate
        person_info_window.setWindowTitle(_translate("person_info_window", "Form"))


