"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MyCaseLib.py']
DATA_FILES = [ 
'example',
'MCLib_Bar_icon.png',
'MCLib_icon_transparent.png',
]

OPTIONS = {
    'iconfile': 'MCLib_icon.icns',
    'includes': [
    'PyQt6',
    'AppKit',
    'qtawesome',
    'functools',
    'datetime',
    'shutil',
    'sqlite3',
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
