"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['MyCaseLib.py']
DATA_FILES = [ 
'example',
'MCLib_Bar_icon.png'
]

OPTIONS = {
    'iconfile': 'MCLib_icon.png',
    'includes': [
    'rumps', 
    'PyQt5'
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
